export type FeaturedImageType = {
    id: number,
    disk: string,
    directory: string,
    visibility: string,
    name: string,
    path: string,
    width: number | null,
    height: number | null,
    size: number,
    type: string,
    ext: string,
    alt: string | null,
    title: string | null,
    description: string | null,
    caption: string | null,
    exif: string | null,
    curations: string | null,
    created_at: string,
    updated_at: string,
    tenant_id: number | null,
    url: string,
}